# Generated by Django 3.0.5 on 2021-05-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacrawling', '0002_auto_20210527_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
